sudo: required
services:
  - docker

before_install:
  - docker build -t aviboinidocker/docker-react-project -f Dockerfile.dev .

script:
  - docker run -e CI=true aviboinidocker/docker-react-project npm run test